### ISSUE TITLE
Update ass tags

### ISSUE THREAD

**Issue by wjans** [IxorTalk/ixortalk-aws-cloudformation#49]
Include and update tags that can be used to include with automatic stop/start tooling.

**Comment by rik2803** [comment]
## Resource tags naming conventions and tag list

To solve dependency issues and include resources in the stop/start flow, these resources can
be tagged. Depending on the resource and the tag, the automatic stop and start will perform
certain actions on those resources.

The tag _namespace_ used for tagging the resources is `<prefix>:ass:<resourcetype>:<description>`, where:

* `<prefix>` is optional, if set, the _Task Definition_ for `aws-delete-tagged-cfn-stacks`
  for that account should have an environment variable `ASS_TAG_PREFIX` with the same value.
* `ass` stands for _Automatic Start and Stop_ and is required and fixed.
* `<resourcetype>` is the lowercase AWS acronym for the service (`s3`, `rds`, ...)
* `<description>` is a (very) short description of the performed action.

### List of existing _ASS_ tags

These tags can be prefixed as described above.

* `ass:cfn:deletion-order`: Determine the order of deletion of the _CloudFormation_ stacks.
  The `stack_deletion_order` (no prefix allowed) is still supported for backward compatibility.
* `ass:s3:clean-bucket-on-stop`: Remove all objects in a bucket before deleting the stack
  that owns the bucket.
* `ass:rds:include`: Stop the RDS instance or cluster after all stacks have been stopped and
  start the RDS instance or cluster before re-creating the _CloudFormation_ stacks.
* `ass:rds:start-wait-until-available`: After starting the RDS instance or cluster, wait until
  the RDS status is `available` before continuing. This can be useful when a DB client can not
  recover when the data source is not available. The legacy tag `start_wait_until_available` is
  still supported for backward compatibility.
